# Generated by Django 5.2.8 on 2025-11-20 13:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='student',
            old_name='library',
            new_name='partner',
        ),
    ]
