# Generated by Django 5.2.8 on 2025-12-02 14:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0003_student_birth_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='student',
            name='birth_date',
        ),
    ]
