# Generated by Django 5.2.8 on 2025-11-20 09:35

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Partner',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255, verbose_name='Nom du partenaire')),
                ('partner_type', models.CharField(choices=[('LIB', 'Librairie'), ('JV', 'Magasin Jeux Vidéo'), ('SUP', 'Superette'), ('CAF', 'Café'), ('BOO', 'Bouquinerie'), ('MAG', 'Magasin Général'), ('IND', 'Indépendant')], default='LIB', max_length=3, verbose_name='Type de partenaire')),
                ('email', models.EmailField(max_length=254, unique=True, verbose_name='Email')),
                ('phone', models.CharField(blank=True, max_length=20, verbose_name='Téléphone')),
                ('contact_person', models.CharField(blank=True, max_length=255, verbose_name='Personne de contact')),
                ('address', models.TextField(blank=True, verbose_name='Adresse')),
                ('commission_per_student', models.DecimalField(decimal_places=2, default=1000, max_digits=10, verbose_name='Commission par élève (DA)')),
                ('status', models.CharField(choices=[('active', 'Actif'), ('inactive', 'Inactif'), ('suspended', 'Suspendu')], default='active', max_length=20, verbose_name='Statut')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Date de création')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Date de mise à jour')),
                ('user', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='partner', to=settings.AUTH_USER_MODEL, verbose_name='Compte utilisateur')),
            ],
            options={
                'verbose_name': 'Partenaire',
                'verbose_name_plural': 'Partenaires',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='PartnershipCode',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('code', models.CharField(max_length=20, unique=True, verbose_name='Code partenaire')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Date de création')),
                ('is_active', models.BooleanField(default=True, verbose_name='Actif')),
                ('library', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='partnership_codes', to='partnerships.partner', verbose_name='Partenaire')),
            ],
            options={
                'verbose_name': 'Code de partenariat',
                'verbose_name_plural': 'Codes de partenariat',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='Montant à payer (DA)')),
                ('remaining_amount', models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='Montant restant (DA)')),
                ('status', models.CharField(choices=[('pending', 'Non payé'), ('partial', 'Partiel'), ('completed', 'Payé'), ('cancelled', 'Annulé')], default='pending', max_length=20, verbose_name='Statut')),
                ('reference', models.CharField(blank=True, max_length=100, verbose_name='Référence de paiement')),
                ('notes', models.TextField(blank=True, verbose_name='Notes')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Date de création')),
                ('completed_at', models.DateTimeField(blank=True, null=True, verbose_name='Date de paiement')),
                ('library', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payments', to='partnerships.partner', verbose_name='Partenaire')),
            ],
            options={
                'verbose_name': 'Paiement',
                'verbose_name_plural': 'Paiements',
                'ordering': ['-created_at'],
            },
        ),
    ]
