# Generated by Django 5.2.8 on 2025-11-20 13:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('partnerships', '0002_paymentreceipt'),
    ]

    operations = [
        migrations.RenameField(
            model_name='partnershipcode',
            old_name='library',
            new_name='partner',
        ),
        migrations.RenameField(
            model_name='payment',
            old_name='library',
            new_name='partner',
        ),
    ]
