# Generated by Django 5.2.8 on 2025-12-02 08:25

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('partnerships', '0003_rename_fk_library_to_partner'),
    ]

    operations = [
        migrations.CreateModel(
            name='PartnershipRequest',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('business_name', models.CharField(max_length=255, verbose_name='Nom du commerce')),
                ('business_type', models.CharField(choices=[('LIB', 'Librairie'), ('JV', 'Magasin Jeux Vidéo'), ('SUP', 'Superette'), ('CAF', 'Café'), ('BOO', 'Bouquinerie'), ('MAG', 'Magasin Général'), ('IND', 'Indépendant')], max_length=3, verbose_name='Type de commerce')),
                ('email', models.EmailField(max_length=254, verbose_name='Email')),
                ('phone', models.CharField(max_length=20, verbose_name='Téléphone')),
                ('address', models.TextField(verbose_name='Adresse')),
                ('message', models.TextField(verbose_name='Message')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Date de création')),
                ('is_processed', models.BooleanField(default=False, verbose_name='Traitée')),
            ],
            options={
                'verbose_name': 'Demande de partenariat',
                'verbose_name_plural': 'Demandes de partenariat',
                'ordering': ['-created_at'],
            },
        ),
    ]
