# Generated by Django 5.2.8 on 2025-12-02 08:38

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('partnerships', '0004_partnershiprequest'),
    ]

    operations = [
        migrations.CreateModel(
            name='PaymentCheckpoint',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('amount_paid', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='Montant payé (DA)')),
                ('checkpoint_date', models.DateTimeField(verbose_name='Date du paiement')),
                ('notes', models.TextField(blank=True, verbose_name='Notes du paiement')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Date de création du checkpoint')),
                ('partner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payment_checkpoints', to='partnerships.partner', verbose_name='Partenaire')),
            ],
            options={
                'verbose_name': 'Point de contrôle paiement',
                'verbose_name_plural': 'Points de contrôle paiements',
                'ordering': ['-checkpoint_date'],
            },
        ),
    ]
