# Generated by Django 5.2.8 on 2025-12-02 08:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('partnerships', '0005_paymentcheckpoint'),
    ]

    operations = [
        migrations.AlterField(
            model_name='paymentcheckpoint',
            name='checkpoint_date',
            field=models.DateTimeField(blank=True, help_text="Laissez vide pour utiliser la date d'aujourd'hui", null=True, verbose_name='Date du paiement'),
        ),
    ]
